### ISSUE TITLE
Redis PVC error

### ISSUE THREAD

**Issue by muhwagwa** [1Password/op-scim-helm#142]
### Your environment

Chart Version: 2.11.4

Helm Version: 3.15.3

Kubernetes Version: 1.30

## What happened?
Error for redis pod : 
`0/4 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.`

Error for pvc : 
`Failed Binding` error with `no persistent volumes available for this claim and no storage class is set`.

## What did you expect to happen?
scim bridge successfully deployed

## Steps to reproduce
EKS deployment with this helm chart. Change the following in the values.yaml file.
 * set `scim.credentials.volume.enabled` to false. (line 11)
 * set `scim.credentials.secrets.enabled` to true. (line 33)
 * set `scim.credentials.secrets.create` to true. (line 35)
 * uncomment `scim.credentials.secrets.scimsession.key.value_base64` and add in your base64 encoded scimsession value between the quotes. (line43)

**Comment by ag-adampike** [comment]
I think this should expected to fail in **every** case if `.Values.scim.credentials.volume.enabled` is set to `false` and the Redis deployment is configured to use a PVC, which is the default for the upstream Bitnami Redis Helm chart.

A mounted volume is not required or expected for Redis in our recommended configuration for SCIM Bridge, since Redis is already configured with snapshots disabled.
