### ISSUE TITLE
Can't override storageClass to gp2

### ISSUE THREAD

**Issue by bourbonfgiles** [1Password/op-scim-helm#32]
Hello,

When looking at the latest release, if I provide an override of `storageClass: gp2` it's never applied. This seems to be missing from the latest release.

Thanks.

**Comment by bourbonfgiles** [comment]
Hi @devillexio this hasn't been populated into the helm repo from what I can see. storageClass isn't there :)

**Comment by devillexio** [comment]
Ah, I see the problem. We have the `storageClass` included in the `values.yaml`, but we hardcoded it to `do-block-storage` in the `op-scim.yaml`, which is a required for Digital Ocean. You can see this on the latest tag for [2.3.0](https://github.com/1Password/op-scim-helm/blob/2.3.0/op-scim-bridge/templates/op-scim.yaml#L91). That means the `storageClass` value in `values.yaml` is never used.

The PR I merged earlier today (#33) includes a I fix for this issue. We should be packaging this fix with the next SCIM bridge (in the next few weeks), but you can use this fix in the interim by doing the following:

1. Checking out the latest changes on the `main` branch
    - note that the config options have changed (see the expanded docs in the readme or `values.yaml`)
2. Package the new changes: `helm package op-scim-bridge`
3. Pass the following parameter to the helm install / upgrade command: `--set scim.credentialsVolume.storageClass=gp2`

Alternatively you can wait for the next release that will also include the fix. Thanks again for reporting the issue! 🙌 I'm going to close this issue since it's been fixed on `main`, but feel free to reopen the issue if necessary.

**Comment by bourbonfgiles** [comment]
@devillexio Thank you so much!
